version: '3'
services:
  proxy:
    build: .
    image: flask_proxy
    container_name: flask_proxy
    ports:
      - "80:5001"
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"